### PR TITLE
change 'mathematical' to 'numerical'

### PR DESCRIPTION
**Pull request by conradsnicta**

### CODE REVIEW

**Review by zoq — APPROVED** [review]
Looks good to me.

**Review by birm — APPROVED** [review]

**Comment by conradsnicta** [comment]
PS. may also want to change the short description on https://github.com/mlpack/ensmallen to:  
"A header-only C++ library for numerical optimization -- http://ensmallen.org"

**Review by rcurtin — APPROVED** [review]
Thanks! :+1:

**Comment by rcurtin** [comment]
> PS. may also want to change the short description on https://github.com/mlpack/ensmallen to:
> "A header-only C++ library for numerical optimization -- http://ensmallen.org"

Done---I also opened mlpack/ensmallen#177. :+1:

**Pull request merged**
