### PR TITLE
update citation to JMLR paper

### PR DESCRIPTION
**Pull request by conradsnicta**
related to https://github.com/mlpack/ensmallen/pull/316/

### CODE REVIEW

**Review by zoq — APPROVED** [review]
Looks good to me.

**Review by shrit — APPROVED** [review]
We can use this one too https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files

**Comment by rcurtin** [comment]
It could be useful to keep the workshop paper too; what do you think?  (Maybe in a separate section below.  The JMLR paper is certainly the main one.)

**Comment by conradsnicta** [comment]
> It could be useful to keep the workshop paper too; what do you think? (Maybe in a separate section below. The JMLR paper is certainly the main one.)

It may confuse folks which one to cite if there are two.  Having one paper (JMLR) is clear.

The JMLR paper cites the tech report, which contains more details.  If someone is really interested they can certainly read the tech report.

**Pull request merged**
